//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zxeltor.StoCombat.Realtime.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CombatLogPath {
            get {
                return ((string)(this["CombatLogPath"]));
            }
            set {
                this["CombatLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("combatlog*.log")]
        public string CombatLogPathFilePattern {
            get {
                return ((string)(this["CombatLogPathFilePattern"]));
            }
            set {
                this["CombatLogPathFilePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int HowLongBeforeNewCombatInSeconds {
            get {
                return ((int)(this["HowLongBeforeNewCombatInSeconds"]));
            }
            set {
                this["HowLongBeforeNewCombatInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyCharacter {
            get {
                return ((string)(this["MyCharacter"]));
            }
            set {
                this["MyCharacter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsEnableInactiveTimeCalculations {
            get {
                return ((bool)(this["IsEnableInactiveTimeCalculations"]));
            }
            set {
                this["IsEnableInactiveTimeCalculations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MinInActiveInSeconds {
            get {
                return ((int)(this["MinInActiveInSeconds"]));
            }
            set {
                this["MinInActiveInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int HowOftenPullDataFromLogFilesSeconds {
            get {
                return ((int)(this["HowOftenPullDataFromLogFilesSeconds"]));
            }
            set {
                this["HowOftenPullDataFromLogFilesSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDebugLoggingEnabled {
            get {
                return ((bool)(this["IsDebugLoggingEnabled"]));
            }
            set {
                this["IsDebugLoggingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUnrealAnnouncementsEnabled {
            get {
                return ((bool)(this["IsUnrealAnnouncementsEnabled"]));
            }
            set {
                this["IsUnrealAnnouncementsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsKeepPlayersInListAfterCombat {
            get {
                return ((bool)(this["IsKeepPlayersInListAfterCombat"]));
            }
            set {
                this["IsKeepPlayersInListAfterCombat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MultiKillWaitInSeconds {
            get {
                return ((int)(this["MultiKillWaitInSeconds"]));
            }
            set {
                this["MultiKillWaitInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCalculateAssitedKills {
            get {
                return ((bool)(this["IsCalculateAssitedKills"]));
            }
            set {
                this["IsCalculateAssitedKills"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsIncludeAssistedKillsInAchievements {
            get {
                return ((bool)(this["IsIncludeAssistedKillsInAchievements"]));
            }
            set {
                this["IsIncludeAssistedKillsInAchievements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int HowOftenParseLogsInSeconds {
            get {
                return ((int)(this["HowOftenParseLogsInSeconds"]));
            }
            set {
                this["HowOftenParseLogsInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsProcessKillingSpreeAnnouncements {
            get {
                return ((bool)(this["IsProcessKillingSpreeAnnouncements"]));
            }
            set {
                this["IsProcessKillingSpreeAnnouncements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsProcessMultiKillAnnouncements {
            get {
                return ((bool)(this["IsProcessMultiKillAnnouncements"]));
            }
            set {
                this["IsProcessMultiKillAnnouncements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int AnnouncementPlaybackVolumePercentage {
            get {
                return ((int)(this["AnnouncementPlaybackVolumePercentage"]));
            }
            set {
                this["AnnouncementPlaybackVolumePercentage"] = value;
            }
        }
    }
}
