//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zxeltor.StoCombat.Analyzer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserCombatDetectionSettings {
            get {
                return ((string)(this["UserCombatDetectionSettings"]));
            }
            set {
                this["UserCombatDetectionSettings"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"JsonVersion\":\"1.5.1\",\"JsonVersionDescription\":\"\",\"Comments\":[\"JsonVersion: Uses" +
            " Semantic Versioning 2.0.0 (Major,Minor,Patch)\",\"GenericGroundMap: When a map is" +
            "n\'t detected when checking CombatMapEntityList, we use this to determine if the " +
            "Combat entity is on a ground based map.\",\"GenericSpaceMap: When a map isn\'t dete" +
            "cted when checking CombatMapEntityList, we use this to determine if the Combat e" +
            "ntity is on a space based map.\",\"EntityExclusionList: This is used to filter out" +
            " game entity ids from the map detect process.\",\"CombatMapEntityList: The main li" +
            "st of map definitions. This collection is used first when trying to detect a map" +
            " for a Combat entity.\"],\"EntityExclusionList\":[{\"IsEnabled\":true,\"Pattern\":\"Spac" +
            "e_Nimbus_Pirate_Distress\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"Vo" +
            "th Power Subcore\",\"IsUniqueToMap\":false}],\"CombatMapEntityList\":[{\"IsEnabled\":tr" +
            "ue,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Spa" +
            "ce_Borg_Dreadnought_Raidisode_Sibrian_Final_Boss\",\"IsUniqueToMap\":true}],\"MapEnt" +
            "ityExclusions\":[],\"Name\":\"Event: Infected Space\"},{\"IsEnabled\":true,\"MaxPlayers\"" +
            ":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Mission_Space_Romu" +
            "lan_Colony_Flagship_Lleiset\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Na" +
            "me\":\"Event: Azure Nebula Rescue\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":" +
            "5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Space_Klingon_Dreadnought_Dsc_Sarc" +
            "ophagus\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Event: Battle A" +
            "t The Binary Stars\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntitie" +
            "s\":[{\"IsEnabled\":true,\"Pattern\":\"Event_Procyon_5_Queue_Krenim_Dreadnaught_Annora" +
            "x\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Event: Battle At Proc" +
            "yon V\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabl" +
            "ed\":true,\"Pattern\":\"Mission_Space_Borg_Queen_Diamond_Brg_Queue_Liberation\",\"IsUn" +
            "iqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Event: Borg Disconnected\"},{\"" +
            "IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":true,\"" +
            "Pattern\":\"Empok Nor\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Eve" +
            "nt: Counterpoint\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\"" +
            ":[{\"IsEnabled\":true,\"Pattern\":\"Space_Crystalline_Entity_2018\",\"IsUniqueToMap\":tr" +
            "ue}],\"MapEntityExclusions\":[],\"Name\":\"Event: Crystalline Entity\"},{\"IsEnabled\":t" +
            "rue,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Ev" +
            "ent_Ico_Qonos_Space_Herald_Dreadnaught\",\"IsUniqueToMap\":true}],\"MapEntityExclusi" +
            "ons\":[],\"Name\":\"Event: Gateway To Grethor\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"Mi" +
            "nPlayers\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Mission_Space_Federation" +
            "_Science_Herald_Sphere\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"" +
            "Event: Herald Sphere\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntit" +
            "ies\":[{\"IsEnabled\":true,\"Pattern\":\"Msn_Dsc_Priors_System_Tfo_Orbital_Platform_1_" +
            "Fed_Dsc\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Event: Operatio" +
            "n Riposte\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsE" +
            "nabled\":true,\"Pattern\":\"_Borg_Dreadnought_R02\",\"IsUniqueToMap\":true}],\"MapEntity" +
            "Exclusions\":[],\"Name\":\"Event: Cure Found\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"Min" +
            "Players\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Space_Klingon_Tos_X3_Batt" +
            "lecruiser\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Event: Days O" +
            "f Doom\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnab" +
            "led\":true,\"Pattern\":\"Msn_Luk_Colony_Dranuur_Queue_System_Upgradeable_Satellite\"," +
            "\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Event: Dranuur Gauntlet\"" +
            "},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":tr" +
            "ue,\"Pattern\":\"Space_Borg_Dreadnought_Raidisode_Khitomer_Intro_Boss\",\"IsUniqueToM" +
            "ap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Event: Khitomer Space\"},{\"IsEnabled\"" +
            ":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"" +
            "Mission_Spire_Space_Voth_Frigate\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[" +
            "],\"Name\":\"Event: Storming The Spire\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlaye" +
            "rs\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Space_Drantzuli_Alpha_Battlesh" +
            "ip\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Event: Swarm\"},{\"IsE" +
            "nabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pat" +
            "tern\":\"Mission_Beta_Lankal_Destructible_Reactor\",\"IsUniqueToMap\":true}],\"MapEnti" +
            "tyExclusions\":[],\"Name\":\"Event: To Hell With Honor\"},{\"IsEnabled\":true,\"MaxPlaye" +
            "rs\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Space_Federatio" +
            "n_Dreadnought_Jupiter_Class_Carrier\",\"IsUniqueToMap\":true},{\"IsEnabled\":true,\"Pa" +
            "ttern\":\"Msn_Luk_Hypermass_Queue_System_Tzk_Protomatter_Facility\",\"IsUniqueToMap\"" +
            ":true}],\"MapEntityExclusions\":[],\"Name\":\"Event: Gravity Kills\"},{\"IsEnabled\":tru" +
            "e,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Spac" +
            "e_Borg_Dreadnought_Hive_Intro\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"" +
            "Name\":\"Event: Hive Space\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapE" +
            "ntities\":[{\"IsEnabled\":true,\"Pattern\":\"Ground_Federation_Capt_Mirror_Runabout_Tf" +
            "o\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Event: Operation Wolf" +
            "\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":t" +
            "rue,\"Pattern\":\"Bluegills_Ground_Boss\",\"IsUniqueToMap\":true}],\"MapEntityExclusion" +
            "s\":[],\"Name\":\"Event: Bug Hunt\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5," +
            "\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Msn_Edren_Queue_Ground_Gorn_Lt_Tos_R" +
            "ange_Rock\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Event: Miner " +
            "Instabilities\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{" +
            "\"IsEnabled\":true,\"Pattern\":\"Msn_Ground_Capt_Mirror_Janeway_Boss_Unkillable\",\"IsU" +
            "niqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Event: Jupiter Station Showd" +
            "own\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled" +
            "\":true,\"Pattern\":\"Mission_Event_Tholian_Invasion_Ext_Boss\",\"IsUniqueToMap\":true}" +
            "],\"MapEntityExclusions\":[],\"Name\":\"Event: Nukara Prime: Transdimensional Tactics" +
            "\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":t" +
            "rue,\"Pattern\":\"Space_Borg_Dreadnought_Wolf359\",\"IsUniqueToMap\":true},{\"IsEnabled" +
            "\":true,\"Pattern\":\"_Wolf359\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Nam" +
            "e\":\"Event: Battle of Wolf 359\"},{\"IsEnabled\":true,\"MaxPlayers\":0,\"MinPlayers\":1," +
            "\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Ground_Renegades_Lt_Gorn_Nimbus_Snip" +
            "er\",\"IsUniqueToMap\":true},{\"IsEnabled\":true,\"Pattern\":\"Ground_Gorn\",\"IsUniqueToM" +
            "ap\":false},{\"IsEnabled\":true,\"Pattern\":\"Beast_Dewan_Arthropod\",\"IsUniqueToMap\":f" +
            "alse},{\"IsEnabled\":true,\"Pattern\":\"Adult Dewan Arthropod\",\"IsUniqueToMap\":false}" +
            ",{\"IsEnabled\":true,\"Pattern\":\"Adult Sand Scorpion\",\"IsUniqueToMap\":false},{\"IsEn" +
            "abled\":true,\"Pattern\":\"Dewan Arthropod\",\"IsUniqueToMap\":false},{\"IsEnabled\":true" +
            ",\"Pattern\":\"Giant Scorpion\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"" +
            "Mature Sand Scorpion\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"Sand S" +
            "corpion\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"Young Dewan Arthrop" +
            "od\",\"IsUniqueToMap\":false}],\"MapEntityExclusions\":[],\"Name\":\"Map: Nimbus\"},{\"IsE" +
            "nabled\":true,\"MaxPlayers\":0,\"MinPlayers\":1,\"MapEntities\":[{\"IsEnabled\":true,\"Pat" +
            "tern\":\"Ground_Tholian\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"Missi" +
            "on_Tholian_Invasion_Trapped_Friend_Starfleet\",\"IsUniqueToMap\":false},{\"IsEnabled" +
            "\":true,\"Pattern\":\"Ground_Tholian_Ensign\",\"IsUniqueToMap\":false},{\"IsEnabled\":tru" +
            "e,\"Pattern\":\"KDF Officer\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"St" +
            "arfleet Officer\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"Tholian Dro" +
            "ne Assistant\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"Trapped Office" +
            "r\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"Worker\",\"IsUniqueToMap\":f" +
            "alse},{\"IsEnabled\":true,\"Pattern\":\"Ground_Tholian_Ensign_2\",\"IsUniqueToMap\":fals" +
            "e},{\"IsEnabled\":true,\"Pattern\":\"Ground_Tholian_Ensign_3\",\"IsUniqueToMap\":false}," +
            "{\"IsEnabled\":true,\"Pattern\":\"Ground_Tholian_Ensign_Noreward\",\"IsUniqueToMap\":fal" +
            "se}],\"MapEntityExclusions\":[],\"Name\":\"Map: Nukara Prime\"},{\"IsEnabled\":true,\"Max" +
            "Players\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Ground_Ela" +
            "chi\",\"IsUniqueToMap\":false}],\"MapEntityExclusions\":[{\"IsEnabled\":true,\"Pattern\":" +
            "\"Ground_Elachi_Ensign_Friendly_Rift\",\"IsUniqueToMap\":false}],\"Name\":\"Event: Defe" +
            "nd Rh\'Ihho Station\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntitie" +
            "s\":[{\"IsEnabled\":true,\"Pattern\":\"Range_Mirror\",\"IsUniqueToMap\":false}],\"MapEntit" +
            "yExclusions\":[],\"Name\":\"Event: Borg Battle Royale\"},{\"IsEnabled\":true,\"MaxPlayer" +
            "s\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"of Ten Unimatrix" +
            " 0047\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Red Alert: Borg\"}" +
            ",{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":tru" +
            "e,\"Pattern\":\"Space_Tholian_Dreadnought_Red_Alert\",\"IsUniqueToMap\":true}],\"MapEnt" +
            "ityExclusions\":[],\"Name\":\"Red Alert: Tholian\"},{\"IsEnabled\":true,\"MaxPlayers\":5," +
            "\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Space_Nakuhl_Constric" +
            "tor_Node_Dreadnaught\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Re" +
            "d Alert: Na\'kuhl\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\"" +
            ":[{\"IsEnabled\":true,\"Pattern\":\"Elachi_Battleship_Player_Pet_Control\",\"IsUniqueTo" +
            "Map\":true}],\"MapEntityExclusions\":[],\"Name\":\"Red Alert: Elachi\"},{\"IsEnabled\":tr" +
            "ue,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"C.S" +
            ".S. Tzen-Torun\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Red Aler" +
            "t: Tzenkethi\"},{\"IsEnabled\":true,\"MaxPlayers\":0,\"MinPlayers\":1,\"MapEntities\":[{\"" +
            "IsEnabled\":true,\"Pattern\":\"Kan\'Keli\",\"IsUniqueToMap\":true},{\"IsEnabled\":true,\"Pa" +
            "ttern\":\"Tak\'Terak\",\"IsUniqueToMap\":true},{\"IsEnabled\":true,\"Pattern\":\"Kan\'Keli\"," +
            "\"IsUniqueToMap\":true},{\"IsEnabled\":true,\"Pattern\":\"Broln’ta Cruiser\",\"IsUniqueTo" +
            "Map\":false},{\"IsEnabled\":true,\"Pattern\":\"Rhas’bej Battleship\",\"IsUniqueToMap\":fa" +
            "lse},{\"IsEnabled\":true,\"Pattern\":\"Shuk-din Frigate\",\"IsUniqueToMap\":false},{\"IsE" +
            "nabled\":true,\"Pattern\":\"Tzenkethi Shield Repair Unit\",\"IsUniqueToMap\":false},{\"I" +
            "sEnabled\":true,\"Pattern\":\"Tzen’tar Dreadnought\",\"IsUniqueToMap\":false}],\"MapEnti" +
            "tyExclusions\":[],\"Name\":\"Map: Gon\'cra System: Tzenkethi Battlezone\"},{\"IsEnabled" +
            "\":true,\"MaxPlayers\":0,\"MinPlayers\":1,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":" +
            "\"Space_Voth_Dreadnaught\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"Sta" +
            "rbase_Player_Fed_T1\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"Voth Fr" +
            "igate\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"Voth Palisade Frigate" +
            "\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"Aceton Drone\",\"IsUniqueToM" +
            "ap\":false},{\"IsEnabled\":true,\"Pattern\":\"Voth Bastion Cruiser\",\"IsUniqueToMap\":fa" +
            "lse},{\"IsEnabled\":true,\"Pattern\":\"Voth Bulwark Battleship\",\"IsUniqueToMap\":false" +
            "},{\"IsEnabled\":true,\"Pattern\":\"Voth Citadel Dreadnought\",\"IsUniqueToMap\":false}," +
            "{\"IsEnabled\":true,\"Pattern\":\"Voth Ward Repair Ship\",\"IsUniqueToMap\":false}],\"Map" +
            "EntityExclusions\":[],\"Name\":\"Map: Voth Battlezone\"},{\"IsEnabled\":true,\"MaxPlayer" +
            "s\":0,\"MinPlayers\":1,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Dactylus Bioship" +
            "\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"Dromias Bio-Cruiser\",\"IsUn" +
            "iqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"Nicor Bioship\",\"IsUniqueToMap\":fa" +
            "lse},{\"IsEnabled\":true,\"Pattern\":\"Heavy Bioplasmic Torpedo\",\"IsUniqueToMap\":fals" +
            "e}],\"MapEntityExclusions\":[],\"Name\":\"Map: Undine Battlezone\"},{\"IsEnabled\":true," +
            "\"MaxPlayers\":0,\"MinPlayers\":1,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Msn_Mu" +
            "_Bz_Badlands_System_Plasma_Controller\",\"IsUniqueToMap\":false},{\"IsEnabled\":true," +
            "\"Pattern\":\"Stationmod_Battlecruiser_Com_Eng_Platform\",\"IsUniqueToMap\":false},{\"I" +
            "sEnabled\":true,\"Pattern\":\"Fleet Support Platform\",\"IsUniqueToMap\":false},{\"IsEna" +
            "bled\":true,\"Pattern\":\"Plasma Control Station\",\"IsUniqueToMap\":false},{\"IsEnabled" +
            "\":true,\"Pattern\":\"Terran Command Battleship\",\"IsUniqueToMap\":false},{\"IsEnabled\"" +
            ":true,\"Pattern\":\"Terran Cruiser\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Patte" +
            "rn\":\"Terran Frigate\",\"IsUniqueToMap\":false}],\"MapEntityExclusions\":[],\"Name\":\"Ma" +
            "p: Badlands\"},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"I" +
            "sEnabled\":true,\"Pattern\":\"Space_Holo_Projector_Jupiter_Tfo\",\"IsUniqueToMap\":true" +
            "},{\"IsEnabled\":true,\"Pattern\":\"Data Thief\",\"IsUniqueToMap\":true},{\"IsEnabled\":tr" +
            "ue,\"Pattern\":\"Jupiter Holo-Projector\",\"IsUniqueToMap\":true},{\"IsEnabled\":true,\"P" +
            "attern\":\"Terran Hacker Ships\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"N" +
            "ame\":\"Event: Iuppiter Iratus\"},{\"IsEnabled\":true,\"MaxPlayers\":1,\"MinPlayers\":1,\"" +
            "MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Starbase 234\",\"IsUniqueToMap\":true}]," +
            "\"MapEntityExclusions\":[],\"Name\":\"Event: Starbase 234\"},{\"IsEnabled\":true,\"MaxPla" +
            "yers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"_Royal_Flush_" +
            "Tfo\",\"IsUniqueToMap\":true}],\"MapEntityExclusions\":[],\"Name\":\"Event: Royal Flush\"" +
            "},{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEnabled\":tr" +
            "ue,\"Pattern\":\"Space_Federation_Cruiser_Vtx_Tfo_Evacuation_Ship\",\"IsUniqueToMap\":" +
            "true}],\"MapEntityExclusions\":[],\"Name\":\"Event: Resistance of Starbase One\"},{\"Is" +
            "Enabled\":true,\"MaxPlayers\":1,\"MinPlayers\":1,\"MapEntities\":[{\"IsEnabled\":true,\"Pa" +
            "ttern\":\"L.S.S. Jaaleet\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"L.S." +
            "S. Reskava\",\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"L.S.S. Treluun\"," +
            "\"IsUniqueToMap\":false},{\"IsEnabled\":true,\"Pattern\":\"L.S.S. Vuut\",\"IsUniqueToMap\"" +
            ":false}],\"MapEntityExclusions\":[],\"Name\":\"Patrol: Rescue and Search\"}],\"GenericG" +
            "roundMap\":{\"IsEnabled\":true,\"MaxPlayers\":5,\"MinPlayers\":5,\"MapEntities\":[{\"IsEna" +
            "bled\":true,\"Pattern\":\"Ground_\",\"IsUniqueToMap\":false}],\"MapEntityExclusions\":[]," +
            "\"Name\":\"Generic Ground\"},\"GenericSpaceMap\":{\"IsEnabled\":true,\"MaxPlayers\":5,\"Min" +
            "Players\":5,\"MapEntities\":[{\"IsEnabled\":true,\"Pattern\":\"Space_\",\"IsUniqueToMap\":f" +
            "alse}],\"MapEntityExclusions\":[],\"Name\":\"Generic Space\"}}")]
        public string DefaultCombatDetectionSettings {
            get {
                return ((string)(this["DefaultCombatDetectionSettings"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StoCombatAnalyzerSettings {
            get {
                return ((string)(this["StoCombatAnalyzerSettings"]));
            }
            set {
                this["StoCombatAnalyzerSettings"] = value;
            }
        }
    }
}
